---
title: Heterogeneous frailties and mortality selection during the first month of life
author: Jonas Schöley, Jim Oeppen, Rune Lindahl-Jacobsen, James W. Vaupel
date: August 11, 2017
output:
  html_document: default
  md_document: default
  pdf_document: default
header-includes: \usepackage{booktabs, longtable}
bibliography: C:/Users/jschoeley/Dropbox/sci/refs/mendeley_bibtex/2016-09-imort_selection.bib
abstract:
  The risk of infant death declines rapidly during the first month following birth. This rapid decline may be explained as a selection process, with the frailest children leaving the population early. A competing explanation situates the mortality decline on the individual level, pointing towards the risky transition of birth and the growth of the child thereafter.
  By analysing individual level data on US births and neonatal deaths we estimate the heterogeneity in the risk of neonatal present in the population. We show the development of the hazard of death over the first 28 days of life for various population strata. Using this information we decompose the neonatal mortality decline into a population level and an individual level component.
  We find that the population level decline in mortality over the first hour of life is significantly influenced by mortality selection, i.e. the frailest infants leaving the population shortly after birth. The subsequent mortality decline predominantly results from mortality changes observed in homogeneous sub-populations. This confirms the common view of the infant mortality age pattern following a shape arising from individual level processes.
---

# Introduction

# Background



## Ontogenescence as an individual level process

## Ontogenescence as a population level process

@Vaupel1983 propose a model for infant mortality that assumes a constant baseline hazard and a multiplicative frailty following a Gamma distribution with variance 500 (!). Commenting on this model @Hougaard1984 hypothesizes that the high mortality during the first year of life and the subsequent rapid decline may in fact be the result of an "extreme frailty distribution" upon birth, i.e. a distribution with a long right tail. He proposes the inverse Gamma distribution as a suitable candidate.

- Feaganes, J. R. (1993, November). Unobservable heterogeneity in Weibull and Poisson Regression Models: An application to the study of infant mortality in North Carolina. University of North Carolina.
    - parametric modelling of unobserved heterogeneity in regression models of infant mortality
    - discusses the effect of unobserved heterogeneity on the parameter estimates in a regression model
    - discusses omitted variables as a source of unobserved heterogeneity

# Data

Estimating the degree of mortality selection in infancy requires knowledge about the hazard of death in as many population strata as possible, after all it is heterogeneity in the risk of death leading to selection effects. A powerfull and publicly available data source are the "NCHS Cohort Linked Birth -- Infant Death Data Files" from the National Center for Health Statistics^[https://www.cdc.gov/nchs/data_access/Vitalstatsonline.htm]. The data set is a complete census of births and infant deaths on the territory of the United States (without its overseas territories) and features most fields present on the birth and death certificates. The size and detail of the data allows us to produce life-tables for thousands of sub-populations, and thus quantifying the heterogeneity in perinatal mortality.

In order to reach the large sample size needed for a reliable estimation of infant mortality in many sub-populations we pool the six birth cohorts 2005--2010. As preliminary analyses have shown that mortality selection is mainly acting during the first month of life, we subset the data to deaths occuring during the 30 days following birth and condition our analysis on the perinatal period. This leaves us with a sample size of 25,143,288 births and 108,999 infant deaths and 762,991,625 person-days under observation.^[Like all statistics in the paper these values are calculated directly from the individual level data which gives the age at death in days.]

In assessing the heterogeneity in neonatal mortality we consider a set of 13 co-varianates grouped into clinical variables, social strata, and maternal risk factors. Observations featuring missing values are never excluded, instead missingness is coded as an explicit category. Our goal is to capture heterogeneity in the risk of death and missings in the co-variates are just another potential source of variability. In recoding variables we strive for a balance between fidelty of the data and sample-size within category.

# Methods

Consider a cohort of newborns stratified into sub-populations $z=1\ldots k$ according to mortality relevant characteristics (e.\,g.~birth-weight, gestation at birth, presence of congenital diseases etc.). For each time-point during infancy we estimate the hazard of death for both the total population, $\bar\mu(x)$, and each sub population, $\mu_z(x)$, as well as the proportion of survivors in each stratum $\pi_z(x)$. Given time points $x_2 > x_1$, how much of the difference of the population hazard at these points is explained by a change of the sub-population hazards and how much due to a change in the population composition?

Decomposition problems similar to the one stated above have been tackled by many fields over the last half century. The proposed solutions can be categorized as either parametric and regression based [@Oaxaca1973, @Blinder1973, @Powers2011] or non-parametric and co-variance based [@Price1970, @Preston1989, @Schoen1992, @Vaupel2002, @Kerr2009, @Vaupel2010a, @Rebke2012]. The latter approach has been formulated using life-table notation, uses aggregate level data and will be quite intuitive to demographers. The regression based approach on the other hand allows for the direct use of individual level survival data which facilitates multivariate decompositions.^[While multivariate extensions of co-variance based approaches exist, they require the calculation of a life-table for each observed combination of variable levels, which, while far from unfeasible, is rather inconvenient. Furthermore continuous variables have to be discretized which is not the case for the regression based decompositions] We will use the co-variance based decomposition method by @Vaupel2010a in order to quantify mortality selection in a continuous-age setting and then proceed to perform a multivariate decomposition of discrete mortality differences between subsequent ages using the regression based method by @Powers2011. In the following sections we describe our application of both methods.

## Covariance based decomposition

In 1970 George Price published a short note in Nature demonstrating that the change in a population trait over a generation can be decomposed into a selection term, representing the co-variance between the level of a trait and its corresponding reproductive value (fitness), and a term for "genetic drift", i.e. the change of traits over generations due to reasons other than selection [@Price1970]. Price noted that his equation not only applies to biological evolution but to all situations where a population characteristic $Y$ changes over time as a consequence of selection, i.e. due to a co-variance between $Y$ and the population growth rates $r$ in the sub-populations conditioned on $Y$.^[He gave the example of changing mean IQ in a cohort of students over time due to selective dropout.]

@Vaupel2002 extend a result by @Preston1989, thereby stating the full Price equation in a demographic context. Let $\dot{\bar{Y}}$ be the age or time derivative of some demographic measure, let $z$ be an index for population strata and $r$ be the relative population growth rate, then, as stated in @Vaupel2002,

$$
\dot{\bar{Y}} = \bar{\dot{Y}}_z + \text{Cov}(Y_z, r_z),
$$

i.e. the derivative of the demographic measure over age or time equals sum of the average derivative of the measure in all population strata and the co-variance between the demographic measures and relative population growth rates conditioned on each stratum.

A special case arises when the population characteristic $Y$ is a mortality rate. Here the population growth rate for each sub-population is fully determined by the population characteristic itself (in the absence of reproduction and migration), i.e. sub-populations with a high mortality will die-out faster than those with lower mortality. Vaupel and Zhang considered this case in their 2010 article "Attrition in heterogeneous cohorts" and provided the expression,

$$
\dot{\bar{\mu}}(x) = \bar{\dot{\mu}}_z(x) - \sigma^2_{\mu_z}(x),
$$

i.e. at any age the change in the average (population level) force of mortality is equal to the difference of the average change in the mortality across all sub-populations and the variance of mortalities in the population. This was proven to be a special case of formula 1. We will use this expression to perform the uni-variate decomposition of the infant mortality age decline.

Let $\pi_z(x) = \frac{\pi_z(0)\ell_z(x)} {\ell(x)}$ be the share of sub-population $z$ at age $x$ on the total population at age $x$, then, in a slight reparametrisation of the respective equations in @Vaupel2010a, we have the weighted averages

$$
\bar\mu(x) = \sum_z \mu_z(x)\pi_z(x),
$$

i.e. the average mortality at age $x$, and

$$
\sigma^2_{\mu_z}(x) = \sum_z \pi_z(x)[\mu_z(x)-\bar\mu(x)]^2
$$

i.e. the variance of the sub-population mortality rates at age $x$, or the *selection component* of the population hazard's derivative, and

$$
\bar{\dot\mu}_z(x) = \sum_z \dot\mu_z(x)\pi_z(x),
$$

i.e. the average derivative of the sub-population hazards, or the *direct component* of the population hazards derivative.

In order to use the continuous-age formulas without modification we interpolate the observed age specific cohort survival probabilities and mortality rates via a cubic spline, thereby having a continuous polynomial representation of the infant life table. Taking the Kaplan-Meier survival estimate for each sub-population at ages 0 (right after birth), 1 hour, 1-6 days, and 1-4 weeks, we fitted a monotone (Hyman filtered) cubic spline to the data points. Dividing the first derivative of the survival spline (density of deaths) by the survival spline yields the continuous hazard function.

## Regression based decomposition

@Oaxaca1973 and @Blinder1973 both predicted the average wages for females and males assuming the co-variate composition of the opposite sex respectively. Using this approach they were able to decompose the gender pay gap into a composition component capturing the wage differential solely explained by the different characteristics of the female vs. male workforce (e.g. in terms of education or past work experience) and the wage differential due to direct wage discrimination (different wages even in the case that males and females have identical characteristics).

Such a decomposition belongs to a set of techniques known as "regression regularization" and has independently been developed in the field of demography, there with groups $A$ and $B$ representing two different ages or periods.

Let $\bar Y_A$ and $\bar Y_B$ be the mean population level mortality rates at two distinct time-point in infancy. $Y_A|Z$ and $Y_B|Z$ are mean mortality rates for the sub-populations defined by their unique combination of co-variate levels $Z$. Fitting separate regression models for groups A and B one estimates two sets of coefficients. The decomposition then is based on producing counter factual predictions from both regression models. By how much would the population mortality have declined between time points $A$ and $B$ if no mortality change at the individual level would have taken place, i.e. if all the change must be due to a change if population composition? Conversely, what population level change would we see, if the composition stays the same? Modelling $\bar Y$ in regression terms as $\bar Y =F(X\beta)$ with $X$ being a matrix of independent variables and $\beta$ the vector of coefficients the decomposition is given by

$$
\bar Y_A - \bar Y_B = \underbrace{F(X_A\beta_A) - F(X_B\beta_A)}_{\text{Selection effect}} + \underbrace{F(X_B\beta_A) - F(X_B\beta_B)}_{\text{Direct effect}}.
$$

# Description of heterogeneity in perinatal mortality

\begingroup\small

\begin{longtable}{rrrrrrr}
\toprule
\multicolumn{1}{c}{ } & \multicolumn{2}{c}{Births} & \multicolumn{2}{c}{Neonatal deaths} & \multicolumn{2}{c}{Probability of neonatal death} \\
\cmidrule(l{2pt}r{2pt}){2-3} \cmidrule(l{2pt}r{2pt}){4-5} \cmidrule(l{2pt}r{2pt}){6-7}
 & N & pct. & D & pct. & by sub-group & frailty\\
\midrule
\endfirsthead
\multicolumn{7}{@{}l}{\textit{(continued)}}\\
\toprule
 & N & pct. & D & pct. & by sub-group & frailty\\
\midrule
\endhead
\addlinespace[0.5em]
\multicolumn{7}{l}{\textbf{Birthweight}}\\
\hspace{1em}Regular & 22,160,115 & 88.1 & 16,392 & 15.3 & 0.0007 & 0.17\\
\hspace{1em}Extremely low & 185,602 & 0.7 & 68,336 & 63.8 & 0.3682 & 86.48\\
\hspace{1em}Very low & 190,214 & 0.8 & 7,473 & 7.0 & 0.0393 & 9.23\\
\hspace{1em}Low & 1,689,585 & 6.7 & 13,552 & 12.7 & 0.0080 & 1.88\\
\hspace{1em}High & 913,008 & 3.6 & 607 & 0.6 & 0.0007 & 0.16\\
\hspace{1em}NA & 4,764 & 0.0 & 690 & 0.6 & 0.1448 & 34.02\\
\multicolumn{7}{l}{\textbf{Gestation at birth}}\\
\hspace{1em}Full term [39, 41) & 11,409,401 & 45.4 & 7,381 & 6.9 & 0.0006 & 0.15\\
\hspace{1em}Extremely preterm <28 & 189,125 & 0.8 & 65,778 & 61.4 & 0.3478 & 81.69\\
\hspace{1em}Very preterm [28, 32) & 313,381 & 1.2 & 9,297 & 8.7 & 0.0297 & 6.97\\
\hspace{1em}Moderate to late preterm [32, 37) & 2,617,899 & 10.4 & 12,039 & 11.2 & 0.0046 & 1.08\\
\hspace{1em}Early term [37, 39) & 7,026,232 & 27.9 & 8,101 & 7.6 & 0.0012 & 0.27\\
\hspace{1em}Late term [41, 42) & 2,095,768 & 8.3 & 1,503 & 1.4 & 0.0007 & 0.17\\
\hspace{1em}Post term [42, 50) & 1,412,844 & 5.6 & 1,348 & 1.3 & 0.0010 & 0.22\\
\hspace{1em}NA & 78,638 & 0.3 & 1,603 & 1.5 & 0.0204 & 4.79\\
\multicolumn{7}{l}{\textbf{5 minute APGAR score}}\\
\hspace{1em}\hspace{1em}0 & 12,839 & 0.1 & 6,751 & 6.3 & 0.5258 & 123.50\\
\hspace{1em}\hspace{1em}1 & 50,282 & 0.2 & 34,119 & 31.9 & 0.6786 & 159.37\\
\hspace{1em}\hspace{1em}2 & 31,895 & 0.1 & 11,658 & 10.9 & 0.3655 & 85.85\\
\hspace{1em}\hspace{1em}3 & 33,168 & 0.1 & 5,959 & 5.6 & 0.1797 & 42.20\\
\hspace{1em}\hspace{1em}4 & 44,678 & 0.2 & 4,535 & 4.2 & 0.1015 & 23.84\\
\hspace{1em}\hspace{1em}5 & 77,575 & 0.3 & 4,877 & 4.6 & 0.0629 & 14.77\\
\hspace{1em}\hspace{1em}6 & 150,444 & 0.6 & 5,958 & 5.6 & 0.0396 & 9.30\\
\hspace{1em}\hspace{1em}7 & 407,844 & 1.6 & 6,924 & 6.5 & 0.0170 & 3.99\\
\hspace{1em}\hspace{1em}8 & 2,227,489 & 8.9 & 7,456 & 7.0 & 0.0033 & 0.79\\
\hspace{1em}\hspace{1em}9 & 19,863,989 & 79.0 & 10,625 & 9.9 & 0.0005 & 0.13\\
\hspace{1em}\hspace{1em}10 & 987,928 & 3.9 & 348 & 0.3 & 0.0004 & 0.08\\
\hspace{1em}\hspace{1em}NA & 1,255,157 & 5.0 & 7,840 & 7.3 & 0.0062 & 1.47\\
\multicolumn{7}{l}{\textbf{Congenital anomalies}}\\
\hspace{1em}None & 25,063,955 & 99.7 & 101,161 & 94.5 & 0.0040 & 0.95\\
\hspace{1em}Least severe & 16,606 & 0.1 & 373 & 0.3 & 0.0225 & 5.28\\
\hspace{1em}Less severe & 20,133 & 0.1 & 422 & 0.4 & 0.0210 & 4.92\\
\hspace{1em}Severe & 42,594 & 0.2 & 5,094 & 4.8 & 0.1196 & 28.09\\
\multicolumn{7}{l}{\textbf{Plurality}}\\
\hspace{1em}Single & 24,286,661 & 96.6 & 87,365 & 81.6 & 0.0036 & 0.84\\
\hspace{1em}Twin & 818,782 & 3.3 & 17,537 & 16.4 & 0.0214 & 5.03\\
\hspace{1em}Triplet & 35,294 & 0.1 & 1,836 & 1.7 & 0.0520 & 12.22\\
\hspace{1em}Quadruplet or higher & 2,551 & 0.0 & 312 & 0.3 & 0.1223 & 28.73\\
\multicolumn{7}{l}{\textbf{Presence of birth injury}}\\
\hspace{1em}No & 5,026,952 & 20.0 & 22,594 & 21.1 & 0.0045 & 1.06\\
\hspace{1em}Yes & 16,820 & 0.1 & 90 & 0.1 & 0.0054 & 1.26\\
\hspace{1em}NA & 20,099,516 & 79.9 & 84,366 & 78.8 & 0.0042 & 0.99\\
\multicolumn{7}{l}{\textbf{Sex}}\\
\hspace{1em}Male & 12,868,992 & 51.2 & 59,511 & 55.6 & 0.0046 & 1.09\\
\hspace{1em}Female & 12,274,296 & 48.8 & 47,539 & 44.4 & 0.0039 & 0.91\\
\multicolumn{7}{l}{\textbf{Education of mother}}\\
\hspace{1em}High school & 4,617,304 & 18.4 & 24,242 & 22.6 & 0.0053 & 1.23\\
\hspace{1em}No education & 22,826 & 0.1 & 159 & 0.1 & 0.0070 & 1.64\\
\hspace{1em}Elementary school & 524,445 & 2.1 & 2,216 & 2.1 & 0.0042 & 0.99\\
\hspace{1em}College & 5,433,108 & 21.6 & 19,346 & 18.1 & 0.0036 & 0.84\\
\hspace{1em}NA & 14,545,605 & 57.9 & 61,087 & 57.1 & 0.0042 & 0.99\\
\multicolumn{7}{l}{\textbf{Race and hispanic origin of mother}}\\
\hspace{1em}Non-Hispanic White & 13,544,931 & 53.9 & 47,328 & 44.2 & 0.0035 & 0.82\\
\hspace{1em}Hispanic & 6,112,854 & 24.3 & 22,008 & 20.6 & 0.0036 & 0.85\\
\hspace{1em}Non-Hispanic Black & 3,651,815 & 14.5 & 30,461 & 28.5 & 0.0083 & 1.96\\
\hspace{1em}Other & 1,651,980 & 6.6 & 5,366 & 5.0 & 0.0032 & 0.76\\
\hspace{1em}NA & 181,708 & 0.7 & 1,887 & 1.8 & 0.0104 & 2.44\\
\multicolumn{7}{l}{\textbf{Martial status of mother}}\\
\hspace{1em}Married & 15,193,469 & 60.4 & 52,456 & 49.0 & 0.0035 & 0.81\\
\hspace{1em}Unmarried & 9,949,819 & 39.6 & 54,594 & 51.0 & 0.0055 & 1.29\\
\multicolumn{7}{l}{\textbf{Residence status of mother}}\\
\hspace{1em}Residents & 18,438,498 & 73.3 & 69,813 & 65.2 & 0.0038 & 0.89\\
\hspace{1em}Intrastate nonresidents & 6,127,338 & 24.4 & 32,620 & 30.5 & 0.0053 & 1.25\\
\hspace{1em}Interstate nonresidents & 532,344 & 2.1 & 4,441 & 4.1 & 0.0083 & 1.96\\
\hspace{1em}Foreign residents & 45,108 & 0.2 & 176 & 0.2 & 0.0039 & 0.92\\
\multicolumn{7}{l}{\textbf{Age of mother}}\\
\hspace{1em}[20, 30) & 13,253,337 & 52.7 & 54,275 & 50.7 & 0.0041 & 0.96\\
\hspace{1em}<16 & 135,237 & 0.5 & 1,095 & 1.0 & 0.0081 & 1.90\\
\hspace{1em}[16, 20) & 2,409,254 & 9.6 & 13,322 & 12.4 & 0.0055 & 1.30\\
\hspace{1em}[30, 40) & 8,665,086 & 34.5 & 34,381 & 32.1 & 0.0040 & 0.93\\
\hspace{1em}40+ & 676,381 & 2.7 & 3,936 & 3.7 & 0.0058 & 1.37\\
\hspace{1em}NA & 3,993 & 0.0 & 41 & 0.0 & 0.0103 & 2.41\\
\multicolumn{7}{l}{\textbf{Alcohol or tobacco use during pregnancy}}\\
\hspace{1em}No & 4,016,467 & 16.0 & 18,042 & 16.9 & 0.0045 & 1.06\\
\hspace{1em}Yes & 1,007,781 & 4.0 & 5,847 & 5.5 & 0.0058 & 1.36\\
\hspace{1em}NA & 20,119,040 & 80.0 & 83,161 & 77.7 & 0.0041 & 0.97\\*\bottomrule\\
\caption{Description of births, deaths and mortality and relative frailty in various population strata. Data: Calculated on the basis of the birth cohort linked birth-infant death data files by the National Center for Health Statistics.}
\end{longtable}\endgroup

![Trajectories of the mortality hazard during the first month of life by clinical strata. The thick red line marks the population hazard, the dotted line marks the hazard for the 'missing value' category. Signs for mortality selection can be seen when the population is stratified by APGAR score, birthweight and gestation at birth. The population hazard in these categories over time approaches the hazard of the least frail sub-populations. Data: Calculated on the basis of the birth cohort linked birth-infant death data files by the National Center for Health Statistics.](./fig/2017-08-18-ilts.pdf)

![Trajectories of the mortality hazard during the first month of life by maternal strata. The thick red line marks the population hazard, the dotted line marks the hazard for the 'missing value' category. Data: Calculated on the basis of the birth cohort linked birth-infant death data files by the National Center for Health Statistics.](./fig/2017-08-24-ilts_mother.pdf)

# Univariate decomposition

\begingroup\small

\begin{longtable}{cccccccc}
\toprule
\multicolumn{1}{c}{Age} & \multicolumn{1}{c}{Population hazard} & \multicolumn{2}{p{3cm}}{Absolute and relative derivative of population hazard} & \multicolumn{2}{p{3cm}}{Absolute and relative direct effect} & \multicolumn{2}{p{3cm}}{Absolute and relative selection effect} \\
\cmidrule(l{2pt}r{2pt}){1-1} \cmidrule(l{2pt}r{2pt}){2-2} \cmidrule(l{2pt}r{2pt}){3-4} \cmidrule(l{2pt}r{2pt}){5-6} \cmidrule(l{2pt}r{2pt}){7-8}
$x$ & $\bar\mu(x)$ & $\dot{\bar{\mu}}(x)$ & $\dot{\bar{\mu}}(x)/\bar\mu(x)$ & $\bar{\dot{\mu}}_z(x)$ & $\bar{\dot{\mu}}_z(x)/\dot{\bar{\mu}}(x)$ & $-\sigma^2_{\mu_z}(x)$ & $-\sigma^2_{\mu_z}(x)/\dot{\bar{\mu}}(x)$\\
\midrule
\endfirsthead
\multicolumn{8}{@{}l}{\textit{(continued)}}\\
\toprule
$x$ & $\bar\mu(x)$ & $\dot{\bar{\mu}}(x)$ & $\dot{\bar{\mu}}(x)/\bar\mu(x)$ & $\bar{\dot{\mu}}_z(x)$ & $\bar{\dot{\mu}}_z(x)/\dot{\bar{\mu}}(x)$ & $-\sigma^2_{\mu_z}(x)$ & $-\sigma^2_{\mu_z}(x)/\dot{\bar{\mu}}(x)$\\
\midrule
\endhead
\addlinespace[0.5em]
\multicolumn{8}{l}{\textbf{Birthweight}}\\
\hspace{1em}0 & 5.3e-04 & -7.8e-04 & -1.46 & -7.5e-04 & 0.97 & -2.5e-05 & 0.03\\
\hspace{1em}1 & 1.8e-04 & -1.3e-04 & -0.74 & -1.3e-04 & 0.98 & -3.1e-06 & 0.02\\
\hspace{1em}24 & 4.1e-06 & -2.0e-07 & -0.05 & -2.0e-07 & 1.00 & -7.5e-10 & 0.00\\
\hspace{1em}168 & 8.8e-07 & -1.7e-09 & -0.00 & -1.7e-09 & 0.99 & -1.9e-11 & 0.01\\
\hspace{1em}672 & 3.5e-07 & -2.6e-10 & -0.00 & -2.6e-10 & 0.99 & -2.1e-12 & 0.01\\
\addlinespace[0.5em]
\multicolumn{8}{l}{\textbf{Gestation at birth}}\\
\hspace{1em}0 & 5.3e-04 & -7.8e-04 & -1.46 & -7.5e-04 & 0.97 & -2.3e-05 & 0.03\\
\hspace{1em}1 & 1.8e-04 & -1.3e-04 & -0.74 & -1.3e-04 & 0.98 & -2.8e-06 & 0.02\\
\hspace{1em}24 & 4.1e-06 & -2.0e-07 & -0.05 & -2.0e-07 & 1.00 & -6.9e-10 & 0.00\\
\hspace{1em}168 & 9.0e-07 & -1.8e-09 & -0.00 & -1.7e-09 & 0.99 & -1.6e-11 & 0.01\\
\hspace{1em}672 & 3.5e-07 & -2.6e-10 & -0.00 & -2.6e-10 & 0.99 & -1.7e-12 & 0.01\\
\addlinespace[0.5em]
\multicolumn{8}{l}{\textbf{5 minute APGAR score}}\\
\hspace{1em}0 & 5.4e-04 & -7.4e-04 & -1.37 & -6.7e-04 & 0.90 & -7.1e-05 & 0.10\\
\hspace{1em}1 & 1.5e-04 & -1.2e-04 & -0.81 & -1.2e-04 & 0.96 & -5.3e-06 & 0.04\\
\hspace{1em}24 & 3.9e-06 & -2.0e-07 & -0.05 & -1.9e-07 & 1.00 & -8.5e-10 & 0.00\\
\hspace{1em}168 & 9.3e-07 & -1.5e-09 & -0.00 & -1.5e-09 & 0.99 & -9.4e-12 & 0.01\\
\hspace{1em}672 & 3.7e-07 & -2.8e-10 & -0.00 & -2.8e-10 & 1.00 & -7.3e-13 & 0.00\\
\addlinespace[0.5em]
\multicolumn{8}{l}{\textbf{Presence and severity of congenital anomalies}}\\
\hspace{1em}0 & 5.3e-04 & -7.6e-04 & -1.44 & -7.6e-04 & 1.00 & -3.6e-07 & 0.00\\
\hspace{1em}1 & 1.9e-04 & -1.4e-04 & -0.74 & -1.4e-04 & 1.00 & -4.7e-08 & 0.00\\
\hspace{1em}24 & 4.5e-06 & -2.3e-07 & -0.05 & -2.3e-07 & 1.00 & -5.3e-11 & 0.00\\
\hspace{1em}168 & 9.8e-07 & -1.6e-09 & -0.00 & -1.6e-09 & 1.00 & -9.6e-13 & 0.00\\
\hspace{1em}672 & 3.8e-07 & -3.0e-10 & -0.00 & -3.0e-10 & 1.00 & -7.7e-14 & 0.00\\
\addlinespace[0.5em]
\multicolumn{8}{l}{\textbf{Plurality}}\\
\hspace{1em}0 & 5.3e-04 & -7.6e-04 & -1.44 & -7.6e-04 & 1.00 & -2.9e-07 & 0.00\\
\hspace{1em}1 & 1.9e-04 & -1.4e-04 & -0.74 & -1.4e-04 & 1.00 & -3.8e-08 & 0.00\\
\hspace{1em}24 & 4.5e-06 & -2.3e-07 & -0.05 & -2.3e-07 & 1.00 & -1.4e-11 & 0.00\\
\hspace{1em}168 & 9.8e-07 & -1.7e-09 & -0.00 & -1.7e-09 & 1.00 & -5.2e-13 & 0.00\\
\hspace{1em}672 & 3.8e-07 & -3.0e-10 & -0.00 & -3.0e-10 & 1.00 & -4.3e-14 & 0.00\\
\addlinespace[0.5em]
\multicolumn{8}{l}{\textbf{Presence of birth injury}}\\
\hspace{1em}0 & 5.3e-04 & -7.6e-04 & -1.44 & -7.6e-04 & 1.00 & -3.8e-10 & 0.00\\
\hspace{1em}1 & 1.9e-04 & -1.4e-04 & -0.74 & -1.4e-04 & 1.00 & -3.2e-11 & 0.00\\
\hspace{1em}24 & 4.6e-06 & -2.3e-07 & -0.05 & -2.3e-07 & 1.00 & -9.8e-15 & 0.00\\
\hspace{1em}168 & 9.8e-07 & -1.7e-09 & -0.00 & -1.7e-09 & 1.00 & -4.1e-15 & 0.00\\
\hspace{1em}672 & 3.8e-07 & -3.0e-10 & -0.00 & -3.0e-10 & 1.00 & -4.1e-16 & 0.00\\
\addlinespace[0.5em]
\multicolumn{8}{l}{\textbf{Sex}}\\
\hspace{1em}0 & 5.3e-04 & -7.6e-04 & -1.44 & -7.6e-04 & 1.00 & -2.2e-09 & 0.00\\
\hspace{1em}1 & 1.9e-04 & -1.4e-04 & -0.74 & -1.4e-04 & 1.00 & -2.5e-10 & 0.00\\
\hspace{1em}24 & 4.6e-06 & -2.3e-07 & -0.05 & -2.3e-07 & 1.00 & -2.7e-13 & 0.00\\
\hspace{1em}168 & 9.8e-07 & -1.7e-09 & -0.00 & -1.7e-09 & 1.00 & -4.6e-15 & 0.00\\
\hspace{1em}672 & 3.8e-07 & -3.0e-10 & -0.00 & -3.0e-10 & 1.00 & -1.0e-15 & 0.00\\
\addlinespace[0.5em]
\multicolumn{8}{l}{\textbf{Education of mother}}\\
\hspace{1em}0 & 5.3e-04 & -7.6e-04 & -1.44 & -7.6e-04 & 1.00 & -4.4e-09 & 0.00\\
\hspace{1em}\hspace{1em}1 & 1.9e-04 & -1.4e-04 & -0.74 & -1.4e-04 & 1.00 & -5.8e-10 & 0.00\\
\hspace{1em}24 & 4.6e-06 & -2.3e-07 & -0.05 & -2.3e-07 & 1.00 & -4.7e-13 & 0.00\\
\hspace{1em}168 & 9.8e-07 & -1.7e-09 & -0.00 & -1.7e-09 & 1.00 & -1.8e-14 & 0.00\\
\hspace{1em}672 & 3.8e-07 & -3.0e-10 & -0.00 & -3.0e-10 & 1.00 & -7.4e-15 & 0.00\\
\addlinespace[0.5em]
\multicolumn{8}{l}{\textbf{Race and hispanic origin of mother}}\\
\hspace{1em}0 & 5.3e-04 & -7.6e-04 & -1.44 & -7.6e-04 & 1.00 & -5.7e-08 & 0.00\\
\hspace{1em}1 & 1.9e-04 & -1.4e-04 & -0.74 & -1.4e-04 & 1.00 & -8.7e-09 & 0.00\\
\hspace{1em}24 & 4.6e-06 & -2.3e-07 & -0.05 & -2.3e-07 & 1.00 & -3.6e-12 & 0.00\\
\hspace{1em}168 & 9.8e-07 & -1.7e-09 & -0.00 & -1.7e-09 & 1.00 & -8.6e-14 & 0.00\\
\hspace{1em}672 & 3.8e-07 & -3.0e-10 & -0.00 & -3.0e-10 & 1.00 & -2.9e-14 & 0.00\\
\addlinespace[0.5em]
\multicolumn{8}{l}{\textbf{Martial status of mother}}\\
\hspace{1em}0 & 5.3e-04 & -7.6e-04 & -1.44 & -7.6e-04 & 1.00 & -1.3e-08 & 0.00\\
\hspace{1em}1 & 1.9e-04 & -1.4e-04 & -0.74 & -1.4e-04 & 1.00 & -2.0e-09 & 0.00\\
\hspace{1em}24 & 4.6e-06 & -2.3e-07 & -0.05 & -2.3e-07 & 1.00 & -1.0e-12 & 0.00\\
\hspace{1em}168 & 9.8e-07 & -1.7e-09 & -0.00 & -1.7e-09 & 1.00 & -2.7e-14 & 0.00\\
\hspace{1em}672 & 3.8e-07 & -3.0e-10 & -0.00 & -3.0e-10 & 1.00 & -1.8e-14 & 0.00\\
\addlinespace[0.5em]
\multicolumn{8}{l}{\textbf{Residence status of mother}}\\
\hspace{1em}0 & 5.3e-04 & -7.6e-04 & -1.44 & -7.6e-04 & 1.00 & -7.6e-09 & 0.00\\
\hspace{1em}1 & 1.9e-04 & -1.4e-04 & -0.74 & -1.4e-04 & 1.00 & -1.1e-09 & 0.00\\
\hspace{1em}24 & 4.6e-06 & -2.3e-07 & -0.05 & -2.3e-07 & 1.00 & -1.3e-12 & 0.00\\
\hspace{1em}168 & 9.8e-07 & -1.7e-09 & -0.00 & -1.7e-09 & 1.00 & -7.9e-14 & 0.00\\
\hspace{1em}672 & 3.8e-07 & -3.0e-10 & -0.00 & -3.0e-10 & 1.00 & -6.3e-15 & 0.00\\
\addlinespace[0.5em]
\multicolumn{8}{l}{\textbf{Age of mother}}\\
\hspace{1em}0 & 5.3e-04 & -7.6e-04 & -1.44 & -7.6e-04 & 1.00 & -4.2e-09 & 0.00\\
1 & 1.9e-04 & -1.4e-04 & -0.74 & -1.4e-04 & 1.00 & -5.8e-10 & 0.00\\
\hspace{1em}24 & 4.6e-06 & -2.3e-07 & -0.05 & -2.3e-07 & 1.00 & -2.8e-13 & 0.00\\
\hspace{1em}168 & 9.8e-07 & -1.7e-09 & -0.00 & -1.7e-09 & 1.00 & -2.0e-14 & 0.00\\
\hspace{1em}672 & 3.8e-07 & -3.0e-10 & -0.00 & -3.0e-10 & 1.00 & -4.8e-15 & 0.00\\
\addlinespace[0.5em]
\multicolumn{8}{l}{\textbf{Alcohol or tobacco use during pregnancy}}\\
\hspace{1em}0 & 5.3e-04 & -7.6e-04 & -1.44 & -7.6e-04 & 1.00 & -1.8e-09 & 0.00\\
\hspace{1em}1 & 1.9e-04 & -1.4e-04 & -0.74 & -1.4e-04 & 1.00 & -1.9e-10 & 0.00\\
\hspace{1em}24 & 4.6e-06 & -2.3e-07 & -0.05 & -2.3e-07 & 1.00 & -1.4e-13 & 0.00\\
\hspace{1em}168 & 9.8e-07 & -1.7e-09 & -0.00 & -1.7e-09 & 1.00 & -1.5e-14 & 0.00\\
\hspace{1em}672 & 3.8e-07 & -3.0e-10 & -0.00 & -3.0e-10 & 1.00 & -6.4e-15 & 0.00\\*\bottomrule\\
\caption{Vaupel-Zhangh decomposition of the hazard of death during the neonatal period. Data: Calculated on the basis of the birth cohort linked birth-infant death data files by the National Center for Health Statistics.}
\end{longtable}\endgroup

# Multivariate decomposition

\begin{table}[!htb]
  \small\centering
    \begin{tabular}{ll*{2}{p{1cm}}*{5}{p{1cm}}}
      \toprule
       & & \multicolumn{2}{c}{$\Delta\mu(x)$ due to} & \multicolumn{5}{c}{Share on compositional change} \\
      \cmidrule(r){3-4}\cmidrule(l){5-9}
      Age interval & Total $\Delta\mu(x)$ & direct change & compos. change & sex & birth-weight & birth defect & 5 min APGAR & Mother's social status \\
      \midrule
      Hour 0 to 24 & 2.86E-03 & 39.4 & 60.6 & 0.00 & 0.16 & 0.04 & 0.80 & 0.00 \\
      Day 2 to 7 & 7.84E-06 & 85.5 & 14.5 & 0.00 & 0.27 & 0.13 & 0.59 & 0.01 \\
      Week 2 to 4 & 1.72E-06 & 91.7 & 8.3 & 0.00 & 0.25 & 0.24 & 0.49 & 0.02 \\
      Month 2 to 12 & 1.69E-06 & 93.7 & 6.3 & 0.00 & 0.52 & 0.20 & 0.28 & 0.00 \\
      \bottomrule
    \end{tabular}
    \caption{Decomposition of the change in the population hazard into adaptation and selection components for infants born in the US 2005--10: 60.6\,\% of the decline in the population mortality hazard over the first day of life are explained by mortality selection. The differences in APGAR score explain 80\,\% of the total selection effect. Data: Calculated on the basis of the birth cohort linked birth-infant death data files by the National Center for Health Statistics.}
    \label{tab:decomp}
\end{table}

# Discussion

# References